In [1]:
import pandas as pd

df = pd.read_csv("data/preproceed/demo_train_qwen3_w2v_mean_sign_sequences.csv")
df.head()

,id,embedding_0,embedding_1,embedding_2,embedding_3,embedding_4,embedding_5,embedding_6,embedding_7,embedding_8,...,sign_id_seq_41,sign_id_seq_42,sign_id_seq_43,sign_id_seq_44,sign_id_seq_45,sign_id_seq_46,sign_id_seq_47,sign_id_seq_48,sign_id_seq_49,label
0,13002137290,0.040171,-0.053081,-0.012036,-0.051393,0.057189,-0.047792,-0.038217,0.080409,-0.077974,...,0,0,0,0,0,0,0,0,0,0
1,13002137290,0.040171,-0.053081,-0.012036,-0.051393,0.057189,-0.047792,-0.038217,0.080409,-0.077974,...,0,0,0,0,0,0,0,0,0,0
2,13003044440,0.024930,0.043008,-0.010266,-0.098438,0.014726,-0.017840,0.042895,0.038497,-0.019084,...,0,0,0,0,0,0,0,0,0,0
3,13003044440,0.024930,0.043008,-0.010266,-0.098438,0.014726,-0.017840,0.042895,0.038497,-0.019084,...,0,0,0,0,0,0,0,0,0,0
4,13003170305,-0.033510,-0.024078,-0.013319,-0.010731,-0.036030,-0.055633,-0.006846,0.017689,-0.013569,...,0,0,0,0,0,0,0,0,0,0

In [2]:
sign_cols = [c for c in df.columns if c.startswith('sign_id_seq_')]
df[sign_cols].head()

,sign_id_seq_0,sign_id_seq_1,sign_id_seq_2,sign_id_seq_3,sign_id_seq_4,sign_id_seq_5,sign_id_seq_6,sign_id_seq_7,sign_id_seq_8,sign_id_seq_9,...,sign_id_seq_40,sign_id_seq_41,sign_id_seq_42,sign_id_seq_43,sign_id_seq_44,sign_id_seq_45,sign_id_seq_46,sign_id_seq_47,sign_id_seq_48,sign_id_seq_49
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
for col in sign_cols:
    # print contain 0 percentage
    print(col, (df[col] == 0).mean())

sign_id_seq_0 0.0
sign_id_seq_1 0.35446172463248476
sign_id_seq_2 0.5441354428110434
sign_id_seq_3 0.6460761025457153
sign_id_seq_4 0.713013176765866
sign_id_seq_5 0.7554791143779133
sign_id_seq_6 0.7911213696665471
sign_id_seq_7 0.817698996055934
sign_id_seq_8 0.8362428289709574
sign_id_seq_9 0.8554141269272141
sign_id_seq_10 0.8695881140193618
sign_id_seq_11 0.8835380064539261
sign_id_seq_12 0.8971965758336321
sign_id_seq_13 0.9073144496235209
sign_id_seq_14 0.9145302975977053
sign_id_seq_15 0.9224072248117605
sign_id_seq_16 0.9312029401219075
sign_id_seq_17 0.9382619218357834
sign_id_seq_18 0.9430911617067049
sign_id_seq_19 0.9475842595912514
sign_id_seq_20 0.9505198996055934
sign_id_seq_21 0.9532202402294729
sign_id_seq_22 0.9567945500179276
sign_id_seq_23 0.9605929544639655
sign_id_seq_24 0.9628563105055575
sign_id_seq_25 0.963416547149516
sign_id_seq_26 0.9658143599856579
sign_id_seq_27 0.9661168877733954
sign_id_seq_28 0.9677751882395124
sign_id_seq_29 0.9677751882395124
sign_id_seq_30 0.9698256543564001
sign_id_seq_31 0.9701730010756544
sign_id_seq_32 0.9705763714593044
sign_id_seq_33 0.9717192542129796
sign_id_seq_34 0.9737921297956257
sign_id_seq_35 0.9749686267479384
sign_id_seq_36 0.9757753675152384
sign_id_seq_37 0.9762347615632844
sign_id_seq_38 0.9768398171387594
sign_id_seq_39 0.9768398171387594
sign_id_seq_40 0.9768398171387594
sign_id_seq_41 0.9768398171387594
sign_id_seq_42 0.9768398171387594
sign_id_seq_43 0.9768398171387594
sign_id_seq_44 0.9768398171387594
sign_id_seq_45 0.9778594478307637
sign_id_seq_46 0.9790023305844389
sign_id_seq_47 0.9790023305844389
sign_id_seq_48 0.9795401577626389
sign_id_seq_49 0.9800891896737182